apiVersion: v1
kind: Service
metadata:
  name: sentinel-backend
  namespace: sentinel
  labels:
    app: sentinel
    component: backend
    tier: application
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: sentinel
    component: backend
